### ISSUE TITLE
Defining urban core for centralization indices

### ISSUE THREAD

**Issue by weikang9009** [pysal/segregation#18]
The definition of urban core is essential to the centralization indices. Right now, the urban core is defined as the geometric center of the centroids of input polygons (e.g. tract boundaries). While this definition is convenient and could be meaningful in some cases, it might not be the best way to define urban core in others. Some other options could be:
* the central business district (CBD)
* the population centroid
* the centroid of the MSA (the dissolved boundary of all tracts)

I think it would be nice to provide these options to users.

Another complication related to measuring the centralization dimension of a MSA is that it could host several cities, each of which has an urban core.

**Comment by knaaptime** [comment]
thats a great point.

IMO the centroid of the MSA has the same drawbacks as using tract centroids, 
and conceptually, its the *employment* center of mass that defines the urban core, at least according to the monocentric model, so I'd argue that using the CBD would be the best option

but doing so would require, e.g. using [lehd](https://lehd.ces.census.gov/data/#lodes)... We dont have a package for working with LEHD, but would sure be useful. Maybe this would be something to consider for `regal` @sjsrey?

**Comment by weikang9009** [comment]
I agree on the drawbacks of using the centroid of the MSA. 

Working with LEHD to define CBD sounds amazing! I am on board!

**Comment by renanxcortes** [comment]
Yes, this is totally a point very worth to refine in the module (I remember that it was even a question raised in the presentation at AAG). I think also that we could add an extra argument allowing multiple options for the user to input what would be considered the city business central. I would also add to the three option that @weikang9009  raised (also the one that @knaaptime raised) to allow the user to input a specific geometry that is present in the GeoDataFrame.

**Comment by knaaptime** [comment]
> I agree on the drawbacks of using the centroid of the MSA.
> 
> Working with LEHD to define CBD sounds amazing! I am on board!

now that i think about it, this could also be an interesting use-case for the spatially-constrained clustering algos in geosnap

**Comment by knaaptime** [comment]
related, @jamgreen  is working on the [lehdr](https://github.com/jamgreen/lehdr) package for R, and he and I were just at UAA discussing the potential for putting together a Python cousin. 

Let's put some time on the calendar to think this through because it would be a great start to the `data` submodule for the regional analysis library (`regal`) we've been been planning

**Comment by knaaptime** [comment]
i wonder how closely you could approximate the CBD, by like, taking the centroid of the most populous [place](ftp://ftp2.census.gov/geo/tiger/TIGER2018/PLACE/) in the MSA, and buffering it out like 2 miles?

**Comment by renanxcortes** [comment]
I've been preparing a pretty nice PR that address this issue with the following new argument for any centralization index:
```
    center        : string, tuple or integer.
                    This defines what is considered to be the center of the spatial context under study.

                    If string, this can be set to:
                        
                        "mean": the center longitude/latitude is the mean of longitudes/latitudes of all units. 
                        "median": the center longitude/latitude is the median of longitudes/latitudes of all units. 
                        "population_weighted_mean": the center longitude/latitude is the mean of longitudes/latitudes of all units weighted by the total population.
                        "largest_population": the center longitude/latitude is the centroid of the unit with largest total population. If there is a tie in the maximum population, the mean of all coordinates will be taken.
                    
                    If tuple, this argument should be the coordinates of the desired center in the form (longitude, latitude).
                    
                    If integer, the center will be the centroid of the polygon from data corresponding to the integer interpreted as index. 
                    For example, if `center = 0` the centroid of the first row of data is used as center, if `center = 1` the second row will be used, and so on.
```

The code is attached!

[spatial_indexes.zip](https://github.com/pysal/segregation/files/3154952/spatial_indexes.zip)

**Comment by renanxcortes** [comment]
> i wonder how closely you could approximate the CBD, by like, taking the centroid of the most populous place in the MSA, and buffering it out like 2 miles?

I had the exactly same idea yesterday hahahah I added this in the center = "largest_population" in the comment above... (code attached but not pushed yet)

**Comment by knaaptime** [comment]
I was giving this some more thought on the way home, and i think there are lots of reasons to include programmatic access to lehd data. It's got annual population and employment totals at the block level, stratified by some useful variables like race, education and wage. we can use it to calculate both residential and employment segregation

**Comment by renanxcortes** [comment]
Guys, I opened a PR here addressing partially the discussion we had here (I think we can work in parallel the LEHD approach). The PR is https://github.com/pysal/segregation/pull/23

For some reason, I couldn't add @weikang9009 as a reviewer... here's what it shows when I try (even when I search for Wei Kang's GitHub username she didn't show up):

![image](https://user-images.githubusercontent.com/22593188/57574783-36326e80-73f4-11e9-9d13-6eb9f3e3379f.png)

Would you have any idea why this might be happening?

Best,
Renan

**Comment by knaaptime** [comment]
what about the center of mass for 2d kernel density on population?

**Comment by dfolch** [comment]
Earlier in this thread it was mentioned to use the center of employment (as opposed to center of population). I think that is the better way to go since it would more closely approximate the common view of "city center" as the business center (or historic center or cultural center or government center) of the region.  One thing that is available right now via cenpy is Zip Code Business Patterns (ZBP) data. I'm not a big fan of zip codes for social science research, but they might be good enough to get an approximate city center. 

Two caveats:
- ZBP easily returns number of establishments, but number of employees requires some assumptions to compute
- Zip codes do not map directly onto other census geographies, so some geo-in-geo rules would need to be established to determine which zips to assign to a region

```python
import cenpy as cen   # using '1.0.0dev'
# Early years (1994 to 2011) follow the pattern ZBPTotal####
api_conn = cen.products.APIConnection('ZBPTotal2011') 
data = api_conn.query(cols=['ESTAB'],  geo_unit='zipcode')

# Recent years (2012 to 2016) follow the pattern ZBP####, which reflects that more data is now available
api_conn = cen.products.APIConnection('ZBP2016')
data = api_conn.query(cols=['ESTAB'],  geo_unit='zipcode')
```

Some other options that are less algorithmic, but may be more culturally based (and inclusive of international locations) is to query a point database (e.g., [Geographic Names Information System](https://geonames.usgs.gov) or [one of many points of interest databases](http://openpois.ogcnetwork.net)). For the largest (sometimes oldest) city in the region:
- Location of city hall
- The map point for the city (essentially where they put the label on the map that says "Los Angeles")

**Comment by knaaptime** [comment]
> Earlier in this thread it was mentioned to use the center of employment (as opposed to center of population). I think that is the better way to go since it would more closely approximate the common view of "city center" as the business center (or historic center or cultural center or government center) of the region. One thing that is available right now via cenpy is Zip Code Business Patterns (ZBP) data. I'm not a big fan of zip codes for social science research, but they might be good enough to get an approximate city center.

a few weeks ago ago i added the [`get_lehd`](https://github.com/spatialucr/geosnap/blob/2d11e24f23831a35ec8c55d0e4f6c0d7bf6ba0fe/geosnap/data/data.py#L617) function to geosnap, which could be moved over here to make this more convenient. I plan to add block data to our [quilt](https://spatialucr.quiltdata.com/b/quilt-cgs) bucket shortly, so this would be pretty straightforward if we want to go the lehd route instead of the zbp route

**Comment by knaaptime** [comment]
allowing the user to pass a pre-defined center is the correct way to handle this. I've got [some musings in my book](https://knaaptime.com/urban_analysis/05_agglomeration/city_center.html) about the best way to find that center, so ready to consider this issue closed
