### ISSUE TITLE
add spatial information theory index

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#2]
![image](https://user-images.githubusercontent.com/4213368/53218670-e2449480-3611-11e9-884f-7e3490ee9add.png)

from Reardon & O'Sullivan 2004

**Comment by renanxcortes** [comment]
Nice, I started to implement it and have question comment. In their notation, i need to work with the population density which is the division of the count and the area. 

![image](https://user-images.githubusercontent.com/22593188/53264369-3db56780-3690-11e9-9ff4-8a6f2a4d5bd6.png)



I develop using the default value of geopandas, but I think it is better to work with squared kilometers, right?

![image](https://user-images.githubusercontent.com/22593188/53264399-56be1880-3690-11e9-9530-f2fb5511b249.png)

**Comment by knaaptime** [comment]
it might be easier to just reproject into a coordinate system that uses meters. So if you're using NYC then you could do `data.to_crs(epse= 32115)` (I think that's the right one). Then the area methods from geopandas should give results in meters

**Comment by knaaptime** [comment]
I'm also working on an exploration that creates the density surface using [network aggregations](https://github.com/UDST/pandana)

**Comment by knaaptime** [comment]
have a look at this https://gist.github.com/knaaptime/538584080e49dcc424568690b915cbe7

**Comment by renanxcortes** [comment]
This is really cool! You implemented the function network_from_bbox in osnap or is this a pandana function?

This is much more elegant in informative than the way that I was doing to build these indexes from Reardon / Osullivan. What I was doing was building the spatial context of that 'tilde' estimates using neighborhoods matrices from libpysal (Queen, knn, etc.) instead of this distance-decay approach with the networks.

**Comment by knaaptime** [comment]
`network_from_bbox` is from [osmnet](https://github.com/UDST/osmnet)

**Comment by knaaptime** [comment]
note these are share surfaces, not density surfaces, but we could calculate those as well...

**Comment by knaaptime** [comment]
> have a look at this [gist.github.com/knaaptime/538584080e49dcc424568690b915cbe7](https://gist.github.com/knaaptime/538584080e49dcc424568690b915cbe7)

the more i think about it, the more i'd like to see the comparative CDF approach applied to this version of the data because it gives a much more detailed picture of the spatial structure

**Comment by renanxcortes** [comment]
> note these are share surfaces, not density surfaces, but we could calculate those as well...

Nice! I think that what I added recently in a new commit, can be used to measure this through the share surfaces.

**Comment by renanxcortes** [comment]
Elijah, take a look at this commit recently pushed:

https://github.com/pysal/segregation/commit/d44ad5ed24b8ce8b36943983827f3091d4d56c93

I used the local environment cited by Reardon (2004) giving by any given weights matrices including the spatial unit itself (all these arguments are flexible and can be modified) (the values were really close to the R seg package, because it was note very clear to me how they assess the local environment). This measure can be calculated to any society with several races as you mentioned in the pandana notebook. However, currently, I just worked with two in order to take advatage of the current structure/framework of the module.

Is this sufficient for you purpose? In addition, are you ok with me adding you in the authors list?

**Comment by knaaptime** [comment]
awesome work! +1 on both.

Closing as is this is now resolved by d44ad5e

**Comment by renanxcortes** [comment]
I decided to reopen this issue as the version that was developed needs to be polished. 

 I've been double checking the measures of the segregation module (in light of the OasisR) and I realized that the Spatial Information Theory index is not reproducing the same results. I realized that actually, I wasn't weighting from the distance of the local context and, perhaps the calculations are a little bit different than the way that I was doing.

![image](https://user-images.githubusercontent.com/22593188/58925401-43ddca00-86fc-11e9-9679-0c1bbdb51073.png)


I think this also would be an opportunity to start implementing multi-group indexes (overall segregation for M groups), such as the one presented in OasisR:

![image](https://user-images.githubusercontent.com/22593188/58925420-51934f80-86fc-11e9-980b-b4213a4bb22e.png)

In this case, a different framework for the module would be open since the input would be, for example, a pandasDataFrame with the columns being the population of all M groups and, no longer, one single variable and the total population variable.

**Comment by knaaptime** [comment]
are we good to close this?

**Comment by renanxcortes** [comment]
Not yet, so the current set of multigroup indexes are virtually "aspatial", even though you can pass a "spatialized" input, such as the network. One thing that I was wanting to add is the actual spatial version of these indexes such as the ones implemented in `seg` R package, so the spatial weights could be something more flexible defining a general local environment such as: https://github.com/cran/seg/blob/master/R/localenv.R

**Comment by knaaptime** [comment]
hm. but the indices themselves are finished, it's just that the input data need to be properly "localized" (basically we want to operate on a modified version of the spatial lag rather than the unit itself)

i think the best thing to do would be to 
- allow each of the spatial functions to take a pysal `W`, 
- modify the W to add the focal unit to its own neighbors list, 
- take the spatial lag of the `mod_W`
- calculate the index on the new `lag_mod_W` values

**Comment by renanxcortes** [comment]
Ok, cool, agreed. Just some code that can be used to draw inspiration starts on line **2709** of:

https://github.com/pysal/segregation/pull/46/commits/b06fc2a1ec425b76cbb8f2946a2c0681ebc797c6

**Comment by renanxcortes** [comment]
The second point can be achieved with line **2805**. We just need to put some love on how to cleverly implement these new functions.

**Comment by knaaptime** [comment]
I think we just need something like 

```python
def localize(data, w):
	new_data = []
	w = pysal.weights.insert_diagonal(w) # attach focal unit to environment
	for y in data:
		new_data.append(lag_spatial(w,y)
	return new_data

```
and then the index is calculated on `new_data`

We could do an if/then depending on whether a `pysal.W` or `pandana.Network` is passed

**Comment by knaaptime** [comment]
this would also be the first step in implementing #19
