### ISSUE TITLE
Order of connectivity may be incorrect in Spatial_Prox_Prof

### ISSUE THREAD

**Issue by sjsrey** [pysal/segregation#5]
Why is the `w`  being passed to manhattan [here](https://github.com/pysal/segregation/blob/master/segregation/spatial_prox_profile.py#L78rl)?
Shouldn't this be the shimbel matrix (i.e., shortest path for each i,j)?

**Comment by renanxcortes** [comment]
Good question! According to Hong (2013), they mention that this term can be estimated through different ways. I chose to follow using the W matrix as they consider in the third paragraph of section 3.2 of their paper in the sentence that starts with "One way of determining..."

**Comment by renanxcortes** [comment]
Just to facilitate what I referred, here's this step highlighted in their paper:

![image](https://user-images.githubusercontent.com/22593188/54886024-68860d80-4e40-11e9-961e-97197b42907d.png)

Does this make sense to you?

**Comment by renanxcortes** [comment]
After discussing this morning, I figured out what you meant and you're right, since the distances are not following the appropriate way as Hong (2013) mention in their paper. More details are explained after the part that I highlighted and, in fact, the Shimbel matrix is more appropriate for this index. I'm working on that and sooner will update this.

**Comment by renanxcortes** [comment]
I realized that the Shimbel matrix can crash when you have islands in your dataset (it keeps running indefinitely). Therefore, I'm reopening this issue to try to figure out a way to overcome this limitation. Any ideas?

I was thinking about:
- building a 'generic Shimbel' in libpysal that would have some tuned way to 'estimate' the degree of the connection of the graph.
- using the Euclidean distances, but I think this will not be the better solution as the values of this index can vary a lot.

**Comment by knaaptime** [comment]
in osnap, we try to handle this situation behind the scenes when users try to create a spatial cluster analysis that has disconnected observations. We use KNN weights to attach the subgraph to its nearest point on the larger connectivity graph. The code is a little tough to follow but starts [here](https://github.com/spatialucr/osnap/blob/3abb2f5d61d4aae6c085e0fde041f9cab58c7ea1/osnap/analyze/analytics.py#L138) 

alternatively, since weights constructors include checks for islands and disconnected components, another option might be to fail with an informative message so that folks are forced to think about how to construct the proper weights matrix.

**Comment by sjsrey** [comment]
Since there is no shortest path between two observations belonging to different components, the Shimbel matrix should have "infinity" there, but the algorithm implicitly assumes a single connected component.

One way to fix the multi-component graph would be to do: [weights.attach_islands](https://libpysal.readthedocs.io/en/latest/generated/libpysal.weights.attach_islands.html#)

**Comment by sjsrey** [comment]
[](https://libpysal.readthedocs.io/en/latest/generated/libpysal.weights.attach_islands.html#libpysal.weights.attach_islands)

**Comment by knaaptime** [comment]
(which is the approach we use in osnap)

**Comment by renanxcortes** [comment]
thank you, interesting! However, looking in more details this problem (I'm looking the internals of the shimbel function profiling, printing intermediate steps)... I think that what I'm facing is actually related to the size of the dataset...
I rerun the shimbel with LA dropping the islands, but the problem persisted (It's been running for more than 30 minutes and the result is still not generated)
This would be just iteration for a single city... so, this would be highlighted with, for example, 500 iterations... and I'm not considering the comparative segregation

But regarding the islands, have you ever faced a problem that you could have islands that attaching only the first neighbor still result in a disconnected graph? for example, having two groups of 'islands' (I think even the attach_islands would not solve the issue):

![image](https://user-images.githubusercontent.com/22593188/55831351-bbf68d80-5ac7-11e9-9d2b-76ec7a7e1136.png)

In this example with only 4 spatial unit (therefore, the size is not a problem here), the shimbel matrix is still not running...

I tried to summarize this in the following notebook (sorry for the lack of reproducibility, but this would be reproducible if you change the paths):
https://github.com/renanxcortes/segregation_refactored/blob/master/notebooks/shimbel_perf.ipynb


ps.: I'm struggling a little bit with that and am considering to build the shortest path using another measure of distance between the centroids, but still don't know...

**Comment by renanxcortes** [comment]
In summary, there are two ways that I'm 'crashing' the shimbel function:

- when you have relatively large geopandas without islands
- when you have a 'weird' island configuration (in this case, even using attach_islands with the knn = 1 I crashed it)

**Comment by knaaptime** [comment]
we should clarify the terminology a bit here. At the code sprint at scipy last year, we tried to make explicit the [conceptual difference](https://github.com/pysal/pysal/issues/1037#issuecomment-393549165) between islands--single observations with no neighbors, and disconnected components--groups of observations that touch each other but are disconnected from the larger graph. So there are no "islands" in the example above but n_components=2, which is why in your example you're getting `UserWarning: The weights matrix is not fully connected. There are 2 components`

I think the problem in your example is that you first try to build a queen matrix, which doesnt return any neighbors because none of the polys are touching. Then you do a KNN=1 weights, which gives you two components (the two observations at the top get attached to one another, and the two observations at the bottom get attached)--but those are still two disconnected components so the graph neighbors graph is never fully connected

**Comment by knaaptime** [comment]
> So there are no "islands" in the example above but n_components=2, which is why in your example you're getting UserWarning: The weights matrix is not fully connected. There are 2 components

actually I spoke too quickly--**all** the observations are islands in the first pass. In the second pass 

`w_aux = libpysal.weights.KNN.from_dataframe(small_gdf, 
                                            ids = small_gdf.index.tolist(),
                                            geom_col = small_gdf._geometry_column_name,k = 1)`

you create a weights object with two components but *no* islands

**Comment by renanxcortes** [comment]
Yes, Eli! You're right! Sorry about that. Actually, all the unit were islands, so my example was not the most appropriate. I'll try to build a better one shortly, to see if this second case is actually a problem.

Thanks!

**Comment by knaaptime** [comment]
these one-off exploration notebooks also make for good gists :)

**Comment by renanxcortes** [comment]
I found an alternative way to build this shimbel matrix much more efficiently. Here's the stream of a current research that I did:

The shortest path problem is a well-know problem: https://en.wikipedia.org/wiki/Shortest_path_problem

In this link, since I wanted all the pairwise shortest paths for the queen matrix, I've seen that the Floyd-Warshall algorith could solve my problem. Then I clicked on it I was redirect to:

https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm

In this link, I've seen that there is an implementation in Python:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.floyd_warshall.html#scipy.sparse.csgraph.floyd_warshall


Therefore, if you pass through our numpy array of the queen matrix (the 'weights' of each connection is 1 and this is an undirected graph) you'll get the same results as the previous shimbel matrix we were using. I'll update the function with this approach.
