### ISSUE TITLE
create `Compute_At` like summmarizing segregation function

### ISSUE THREAD

**Issue by renanxcortes** [pysal/segregation#74]
Following what was discussed in https://github.com/pysal/segregation/pull/73#discussion_r296344366, the idea is to create a function that would only calculate a set of functions given by the user, rather than all the measures that could take more time.

**Comment by knaaptime** [comment]
the original intent for this issue was a function that would specify a subset of segregation indices to be computed all at once. We wanted to provide a subset option since some of the more computationally-intensive indices could slow things down. But given our parallelized implementations, i think this is covered by our [batch functions](https://pysal.org/segregation/api.html#batch-computation) which are performant enough to compute everything. I'm going to close this, but we can reconsider if folks want
