### ISSUE TITLE
[ENH] extend inference framework to multigroup indices

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#86]

**Comment by renanxcortes** [comment]
One the options for this is to use the `bootstrap` approach present in SingleValueTest. I think we could also compare two values of multigroup segregation measures with the `random_label` approach of TwoValueTest.

**Comment by renanxcortes** [comment]
Should we create different classes for these tests (Like `SingleValueMultiTest` or `TwoValueMultiTest`) or we, somehow, allow multigroup measures for the same class? I don't have a strong opinion, but I have a sense that if we go with the second option the class can get a little funky since the approaches for each type of index can be dependent on the api and nature of the input data.

**Comment by renanxcortes** [comment]
On the other hand, creating in the same class, this keeps the api more consistent. In this case, I would create an internal check to see if the input class is multigroup or not (some kind of string check) and then tweak the function accordingly to the input.

For example, the analogous of the `"evenness"` approach, would be generating a multinomial distribution with the global probability vector of the compositions. The analogous of `"bootstrap"` would be just performing the bootstrap similar to the one group value and so on.

**Comment by renanxcortes** [comment]
Closing as this was addressed in https://github.com/pysal/segregation/pull/122.
