### ISSUE TITLE
warn for indices that expect certain projections

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#96]
DistanceDecayExposure for example, expects wgs84. We decided against implicit reprojection, but we could do a check and raise a warning if we cant determine the crs is wgs84

**Comment by renanxcortes** [comment]
Hm.. I'm not sure if I follow... this expectation is due to the usage of `euclidean_distances` in line https://github.com/pysal/segregation/blob/44a10594c46aa64682ddc748e640149f782baa08/segregation/spatial/spatial_indexes.py#L1244?
BTW, I think that we can improve these distances with the proper projections and so on... working with geodesic distance or something like this!

**Comment by knaaptime** [comment]
![image](https://user-images.githubusercontent.com/4213368/60531955-047dab80-9cb1-11e9-8696-04f35dfc1608.png)

the original CRS is albers equal area, and if you try to compute DDE, you get 0. If you reproject into wgs84, you get 0.23

we might just check whether the crs is epsg4236 and warn if not. But agree, a more flexible handling of distance calculation would be prefereable

**Comment by ljwolf** [comment]
a ‘metric’ argument might be useful... that’d let you specify the right metric, and use haversine if the distances are in lat/lng

**Comment by renanxcortes** [comment]
> a ‘metric’ argument might be useful... that’d let you specify the right metric, and use haversine if the coordinates are in lat/lng

I was thinking about something like this. Would you have some example somewhere that I could draw inspiration from? :)

**Comment by ljwolf** [comment]
This would be a good ref. 

https://github.com/scipy/scipy/blob/v1.3.0/scipy/spatial/distance.py#L1736

I'd do `euclidean`, unless someone sends a crs with a units field in degrees?

**Comment by renanxcortes** [comment]
> This would be a good ref.
> 
> https://github.com/scipy/scipy/blob/v1.3.0/scipy/spatial/distance.py#L1736
> 
> I'd do `euclidean`, unless someone sends a crs with a units field in degrees?

Thanks! Ok, but what about the above `aea` example that the units is in `m`? Shouldn't the haversine be applied to that case?

**Comment by knaaptime** [comment]
na its good, the meters means its already projected into a plane

**Comment by renanxcortes** [comment]
So, just for registration, the first example using the old only euclidean based measures was returning zero because of the magnitudes of the number of the albers equal projection. These are the centroids number:

![image](https://user-images.githubusercontent.com/22593188/60554716-97d4d200-9ced-11e9-8fc6-2bd240fea95f.png)

which leads to these numbers after:

```
c = np.exp(-dist)
Pij = np.multiply(c, t) / np.sum(np.multiply(c, t), axis=1)
DDxPy = (x / X * np.nansum(np.multiply(Pij, y / t), axis=1)).sum()
``` 

![image](https://user-images.githubusercontent.com/22593188/60554764-ceaae800-9ced-11e9-8357-9e22de1e66a3.png)


Since DistanceDecayExposure uses `np.nansum` the resulting value was zero. I think if we rerun with this new haversine metric, the resulting value will make more sense.

**Comment by renanxcortes** [comment]
Ok, after discussing here with @knaaptime , things got clearer for me. So, actually using the haversine distance with albers projection is not correct since this crs is already projected to a planar plane. So, what we could do in this case is: if any problem due to the magnitude of the number occurs and generates nan in that distance matrix, raise a ValueError to the user.

Besides that, assuming that we'd like to help our users to use these functions, we need to create a bunch of specific tests using the .crs attribute of the input data. The idea is: if we "suspect" that the user is working with spherical coordinates, raise a warning saying: "It seems like you're working with unprojected coordinate system. Therefore, we recommend to set `metric = haversine`." but in any case calculate the index, because these tests might not capture different funky ways that the .crs might be. Did I get it right, @knaaptime?

**Comment by renanxcortes** [comment]
So, this is partially solved due to https://github.com/pysal/segregation/pull/100. However, I still think that a set of tests/conditions for the input of the GeoPandas to let the user aware of it would be useful. However, now the user can choose between `euclidean` or `haversine` distances but it is up to him to know the nature of his GeoDataFrame.

**Comment by knaaptime** [comment]
with the [new pyproj](https://github.com/geopandas/geopandas/pull/1292/files) integrated into geopandas, it should be much easier to create checks for CRS versions. Re-upping this thread to remind myself to revisit and rewrite those checks

**Comment by knaaptime** [comment]
this is breaking, e.g. `compute_segregation_profile` because it tries to introspect the `.crs` attribute with dict notation, but the CRS object isnt a dict anymore

**Comment by knaaptime** [comment]
geopandas has better CRS handling now (warnings for mismatches and warning when using distance with geometric proj) so closing this here
